services:
  setup:
    image: ghcr.io/movementlabsxyz/suzuka-full-node-setup:${CONTAINER_REV}
    container_name: setup
    environment:
      DOT_MOVEMENT_PATH: /.movement
      # needs to have a connection to the m1-da-light-node
      MAPTOS_CHAIN_ID: ${MAPTOS_CHAIN_ID}
      M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL: ${M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL:?M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL is not set}
      M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME: ${M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME:?M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME is not set}
      M1_DA_LIGHT_NODE_CONNECTION_PORT: ${M1_DA_LIGHT_NODE_CONNECTION_PORT:?M1_DA_LIGHT_NODE_CONNECTION_PORT is not set}
      INDEXER_PROCESSOR_POSTGRES_CONNECTION_STRING: postgres://postgres:password@postgres:5432/postgres
      AWS_REGION: ${AWS_REGION:?AWS_REGION is not set}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MOVEMENT_SYNC: ${MOVEMENT_SYNC:?MOVEMENT_SYNC is not set}
      MAYBE_RUN_LOCAL: "false"
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
      # mount if exists
      # - awscreds:/root/.aws/config:ro

    healthcheck:
      test: [ "CMD-SHELL", "echo 'health check'" ]
      retries: 10
      interval: 10s
      timeout: 5s

  # turn off underlying da light nodes
  celestia-light-node:
    image: busybox
    container_name: celestia-light-node
    command: sleep infinity
    environment:
      - DOT_MOVEMENT_PATH=/.movement
      - CELESTIA_RPC_ADDRESS=celestia-light-node:26657
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      setup:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "echo 'health check'" ]
      retries: 3
      start_period: 3s
    restart: on-failure:3

  # turn off celestia-light-node-synced
  celestia-light-node-synced:
    image: busybox
    container_name: celestia-light-node-synced
    command: echo "No sync check when following."
    environment:
      - DOT_MOVEMENT_PATH=/.movement
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      celestia-light-node:
        condition: service_healthy

  m1-da-light-node-celestia-appd:
    image: ghcr.io/movementlabsxyz/m1-da-light-node-celestia-appd:${CONTAINER_REV}
    container_name: m1-da-light-node-celestia-appd
    environment:
      DOT_MOVEMENT_PATH: /.movement
      CELESTIA_RPC_ADDRESS: m1-da-light-node-celestia-appd:26657
      MAPTOS_CHAIN_ID: ${MAPTOS_CHAIN_ID}
      M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL: ${M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL:?M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL is not set}
      M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME: ${M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME:?M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME is not set}
      M1_DA_LIGHT_NODE_CONNECTION_PORT: ${M1_DA_LIGHT_NODE_CONNECTION_PORT:?M1_DA_LIGHT_NODE_CONNECTION_PORT is not set}
      INDEXER_PROCESSOR_POSTGRES_CONNECTION_STRING: postgres://postgres:password@postgres:5432/postgres
      AWS_REGION: ${AWS_REGION:?AWS_REGION is not set}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MOVEMENT_SYNC: ${MOVEMENT_SYNC:?MOVEMENT_SYNC is not set}
      MAYBE_RUN_LOCAL: "false"
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      setup:
        condition: service_healthy
    ports:
      - "26657:26657"
      - "9090:9090"
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv 0.0.0.0 26657" ]
      retries: 10
      interval: 10s
      timeout: 5s
    restart: on-failure:3

  m1-da-light-node-celestia-bridge:
    image: ghcr.io/movementlabsxyz/m1-da-light-node-celestia-bridge:${CONTAINER_REV}
    container_name: m1-da-light-node-celestia-bridge
    environment:
      DOT_MOVEMENT_PATH: /.movement
      MAPTOS_CHAIN_ID: ${MAPTOS_CHAIN_ID}
      M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL: ${M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL:?M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL is not set}
      M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME: ${M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME:?M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME is not set}
      M1_DA_LIGHT_NODE_CONNECTION_PORT: ${M1_DA_LIGHT_NODE_CONNECTION_PORT:?M1_DA_LIGHT_NODE_CONNECTION_PORT is not set}
      INDEXER_PROCESSOR_POSTGRES_CONNECTION_STRING: postgres://postgres:password@postgres:5432/postgres
      AWS_REGION: ${AWS_REGION:?AWS_REGION is not set}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MOVEMENT_SYNC: ${MOVEMENT_SYNC:?MOVEMENT_SYNC is not set}
      MAYBE_RUN_LOCAL: "false"
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    ports:
      - "26658:26658"
    depends_on:
      setup:
        condition: service_healthy
      m1-da-light-node-celestia-appd:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv 0.0.0.0 26658" ]
      retries: 10
      interval: 10s
      timeout: 5s
    restart: on-failure:3

  m1-da-light-node:
    image: ghcr.io/movementlabsxyz/m1-da-light-node:${CONTAINER_REV}
    container_name: m1-da-light-node
    environment:
      - DOT_MOVEMENT_PATH=/.movement
      - MOVEMENT_TIMING=info
      - M1_DA_LIGHT_NODE_TIMING_LOG=/.movement/m1-da-light-node-timing.log
      - RUST_BACKTRACE=1
      - MAPTOS_CHAIN_ID=${MAPTOS_CHAIN_ID}
      - M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL=${M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL:?M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL is not set}
      - M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME=${M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME:?M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME is not set}
      - M1_DA_LIGHT_NODE_CONNECTION_PORT=${M1_DA_LIGHT_NODE_CONNECTION_PORT:?M1_DA_LIGHT_NODE_CONNECTION_PORT is not set}
      - INDEXER_PROCESSOR_POSTGRES_CONNECTION_STRING=postgres://postgres:password@postgres:5432/postgres
      - AWS_REGION=${AWS_REGION:?AWS_REGION is not set}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MOVEMENT_SYNC=${MOVEMENT_SYNC:?MOVEMENT_SYNC is not set}
      - MAYBE_RUN_LOCAL="false"
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      celestia-light-node-synced:
        condition: service_completed_successfully
    ports:
      - "30730:30730"
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv 0.0.0.0 30730" ]
      retries: 10
      interval: 10s
      timeout: 5s
    restart: on-failure:3

  suzuka-full-node:
    image: ghcr.io/movementlabsxyz/suzuka-full-node:${CONTAINER_REV}
    container_name: suzuka-full-node
    environment:
      - DOT_MOVEMENT_PATH=/.movement
      - MOVEMENT_TIMING=info
      - SUZUKA_TIMING_LOG=/.movement/suzuka-timing.log
      - RUST_BACKTRACE=1
      - MAPTOS_CHAIN_ID=${MAPTOS_CHAIN_ID}
      - M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL=${M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL:?M1_DA_LIGHT_NODE_CONNECTION_PROTOCOL is not set}
      - M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME=${M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME:?M1_DA_LIGHT_NODE_CONNECTION_HOSTNAME is not set}
      - M1_DA_LIGHT_NODE_CONNECTION_PORT=${M1_DA_LIGHT_NODE_CONNECTION_PORT:?M1_DA_LIGHT_NODE_CONNECTION_PORT is not set}
      - INDEXER_PROCESSOR_POSTGRES_CONNECTION_STRING=postgres://postgres:password@postgres:5432/postgres
      - AWS_REGION=${AWS_REGION:?AWS_REGION is not set}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MOVEMENT_SYNC=${MOVEMENT_SYNC:?MOVEMENT_SYNC is not set}
      - MAYBE_RUN_LOCAL="false"
    volumes:
      - ${DOT_MOVEMENT_PATH}:/.movement
    depends_on:
      - m1-da-light-node
    ports:
      - "30731:30731"
      - "30734:30734"
      - "8080:30731"
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv 0.0.0.0 30731" ]
      retries: 10
      interval: 10s
      timeout: 5s
    restart: on-failure:5
